In [13]:
import pandas as pd
import glob

In [100]:
data_dir = "/Users/katybarone/Documents/projects/tennis/"
atp_year_lst = glob.glob(data_dir + "atp_matches*.csv")

matches_dfs = []
for year in atp_year_lst[3:4]:
    df_temp = pd.read_csv(year)
    
    matches_dfs.append(df_temp)

df_matches = pd.concat(matches_dfs, ignore_index=True)

df_matches

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,2023-9900,United Cup,Hard,18,A,20230102,300,126203,3.0,NaN,...,62.0,47.0,15.0,12.0,9.0,9.0,9.0,3355.0,16.0,2375.0
1,2023-9900,United Cup,Hard,18,A,20230102,299,126207,NaN,NaN,...,12.0,8.0,3.0,4.0,1.0,3.0,19.0,2000.0,23.0,1865.0
2,2023-9900,United Cup,Hard,18,A,20230102,296,126203,3.0,NaN,...,62.0,51.0,7.0,12.0,2.0,2.0,9.0,3355.0,10.0,2905.0
3,2023-9900,United Cup,Hard,18,A,20230102,295,126207,NaN,NaN,...,41.0,26.0,12.0,9.0,6.0,9.0,19.0,2000.0,245.0,220.0
4,2023-9900,United Cup,Hard,18,A,20230102,292,126774,1.0,NaN,...,58.0,48.0,18.0,16.0,1.0,2.0,4.0,5550.0,16.0,2375.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2981,2023-M-DC-2023-WG2-PO-RSA-LUX-01,Davis Cup WG2 PO: RSA vs LUX,NaN,4,D,20230204,5,202335,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1717.0,1.0
2982,2023-M-DC-2023-WG2-PO-TUN-CYP-01,Davis Cup WG2 PO: TUN vs CYP,NaN,4,D,20230203,1,117365,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,990.0,11.0,279.0,190.0
2983,2023-M-DC-2023-WG2-PO-TUN-CYP-01,Davis Cup WG2 PO: TUN vs CYP,NaN,4,D,20230203,2,121411,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,364.0,131.0,894.0,15.0
2984,2023-M-DC-2023-WG2-PO-TUN-CYP-01,Davis Cup WG2 PO: TUN vs CYP,NaN,4,D,20230203,4,144949,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,894.0,15.0,285.0,184.0
2985,2023-M-DC-2023-WG2-PO-TUN-CYP-01,Davis Cup WG2 PO: TUN vs CYP,NaN,4,D,20230203,5,121411,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,364.0,131.0,990.0,11.0

In [16]:
atp_100 = pd.read_csv(data_dir + "top_100.csv")
print(len(atp_100))

# Auger-Aliassime and Jan-Lennard need to not have dashes, O'connect can't have an apostrophe
atp_100['name'] = atp_100['name'].str.replace("-", " ")
atp_100['name'] = atp_100['name'].str.replace("'", "")

print(atp_100[atp_100['name'].str.contains("Felix")])
print(atp_100[atp_100['name'].str.contains("Lennard")])
print(atp_100[atp_100['name'].str.contains("Christopher")])

atp_100 = atp_100.merge(df_matches[["loser_name", "loser_id"]], left_on="name", right_on="loser_name", how="inner")

atp_100 = atp_100.drop_duplicates()
atp_100 = atp_100.drop(columns="loser_name", axis=1)
atp_100 = atp_100.rename(columns={"loser_id":"id"})

print(len(atp_100))

100
    rank                   name country
20    21  Felix Auger Aliassime     CAN
    rank                name country
37    38  Jan Lennard Struff     GER
    rank                  name country
86    87  Christopher Oconnell     AUS
100

In [17]:
atp_100.head()

     rank              name country      id
0       1     Jannik Sinner     ITA  206173
81      2  Alexander Zverev     GER  100644
244     3    Carlos Alcaraz     ESP  207989
292     4    Novak Djokovic     SRB  104925
365     5   Daniil Medvedev     RUS  106421

In [6]:
atp_100.to_csv("atp_100_withIDs.csv", index=False)

In [18]:
top_ids = atp_100['id'].values
df_matches.to_csv("atp_matches_all.csv", index=False)
df_100_matches = df_matches[(df_matches['loser_id'].isin(top_ids)) & (df_matches['winner_id'].isin(top_ids))]
df_100_matches.to_csv("atp_100_matches2.csv", index=False)
df_100_matches.head()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
8,2019-M020,Brisbane,Hard,32,A,20181231,292,200282,7.0,NaN,...,39.0,30.0,3.0,9.0,3.0,6.0,31.0,1298.0,72.0,715.0
17,2019-M020,Brisbane,Hard,32,A,20181231,282,200282,7.0,NaN,...,31.0,18.0,4.0,8.0,4.0,9.0,31.0,1298.0,147.0,367.0
24,2019-M020,Brisbane,Hard,32,A,20181231,273,105777,6.0,NaN,...,33.0,21.0,7.0,9.0,0.0,3.0,19.0,1835.0,75.0,701.0
28,2019-0451,Doha,Hard,32,A,20181231,299,105138,7.0,NaN,...,72.0,48.0,27.0,16.0,6.0,8.0,24.0,1605.0,1.0,9045.0
34,2019-0451,Doha,Hard,32,A,20181231,293,104925,1.0,NaN,...,53.0,33.0,16.0,13.0,2.0,6.0,1.0,9045.0,36.0,1122.0

In [11]:
df_100_matches.to_csv("atp_100_matches2.csv", index=False)

In [12]:
len(df_100_matches)

4865

In [101]:
df_matches.sort_values('tourney_date')

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,2023-9900,United Cup,Hard,18,A,20230102,300,126203,3.0,NaN,...,62.0,47.0,15.0,12.0,9.0,9.0,9.0,3355.0,16.0,2375.0
78,2023-2843,Adelaide 1,Hard,32,A,20230102,270,200615,NaN,Q,...,45.0,33.0,11.0,11.0,2.0,4.0,120.0,469.0,6.0,4195.0
77,2023-2843,Adelaide 1,Hard,32,A,20230102,271,106218,NaN,NaN,...,74.0,51.0,38.0,18.0,10.0,12.0,61.0,776.0,68.0,740.0
76,2023-2843,Adelaide 1,Hard,32,A,20230102,272,111456,NaN,NaN,...,25.0,16.0,6.0,5.0,0.0,2.0,63.0,775.0,67.0,741.0
75,2023-2843,Adelaide 1,Hard,32,A,20230102,273,106415,NaN,NaN,...,57.0,40.0,16.0,14.0,7.0,11.0,36.0,1134.0,11.0,2888.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2761,2023-7696,NextGen Finals,Hard,8,F,20231127,290,209098,6.0,NaN,...,43.0,29.0,13.0,11.0,9.0,11.0,110.0,582.0,70.0,756.0
2765,2023-7696,NextGen Finals,Hard,8,F,20231127,286,209098,6.0,NaN,...,50.0,36.0,14.0,12.0,0.0,2.0,110.0,582.0,185.0,326.0
2764,2023-7696,NextGen Finals,Hard,8,F,20231127,287,209406,8.0,NaN,...,37.0,22.0,8.0,10.0,5.0,10.0,185.0,326.0,97.0,653.0
2762,2023-7696,NextGen Finals,Hard,8,F,20231127,289,209414,2.0,NaN,...,41.0,28.0,11.0,11.0,5.0,10.0,70.0,756.0,185.0,326.0
2759,2023-7696,NextGen Finals,Hard,8,F,20231127,292,208134,7.0,NaN,...,52.0,42.0,20.0,15.0,3.0,5.0,115.0,549.0,100.0,640.0

In [28]:
df_matches.isna().sum()

tourney_id                0
tourney_name              0
surface                  53
draw_size                 0
tourney_level             0
tourney_date              0
match_num                 0
winner_id                 0
winner_seed           13376
winner_entry          19724
winner_name               0
winner_hand               3
winner_ht               585
winner_ioc                0
winner_age                5
loser_id                  0
loser_seed            17350
loser_entry           17914
loser_name                0
loser_hand               30
loser_ht               1054
loser_ioc                 0
loser_age                12
score                     0
best_of                   0
round                     0
minutes                 907
w_ace                   709
w_df                    709
w_svpt                  709
w_1stIn                 709
w_1stWon                709
w_2ndWon                709
w_SvGms                 708
w_bpSaved               709
w_bpFaced               709
l_ace                   709
l_df                    709
l_svpt                  709
l_1stIn                 709
l_1stWon                709
l_2ndWon                709
l_SvGms                 708
l_bpSaved               709
l_bpFaced               709
winner_rank             105
winner_rank_points      105
loser_rank              290
loser_rank_points       290
dtype: int64

In [29]:
df_matches.dropna(subset=['minutes', 'w_bpSaved'], axis=0, inplace=True)
df_matches.isna().sum()

tourney_id                0
tourney_name              0
surface                   0
draw_size                 0
tourney_level             0
tourney_date              0
match_num                 0
winner_id                 0
winner_seed           12633
winner_entry          18795
winner_name               0
winner_hand               3
winner_ht               471
winner_ioc                0
winner_age                1
loser_id                  0
loser_seed            16512
loser_entry           17001
loser_name                0
loser_hand               24
loser_ht                840
loser_ioc                 0
loser_age                 6
score                     0
best_of                   0
round                     0
minutes                   0
w_ace                     0
w_df                      0
w_svpt                    0
w_1stIn                   0
w_1stWon                  0
w_2ndWon                  0
w_SvGms                   0
w_bpSaved                 0
w_bpFaced                 0
l_ace                     0
l_df                      0
l_svpt                    0
l_1stIn                   0
l_1stWon                  0
l_2ndWon                  0
l_SvGms                   0
l_bpSaved                 0
l_bpFaced                 0
winner_rank              65
winner_rank_points       65
loser_rank              198
loser_rank_points       198
dtype: int64

In [102]:
# Define initial ELO rating (common initial rating)
INITIAL_ELO = 1500

# Dictionary to store player Elo ratings for all surfaces
player_elo = {}

# Surfaces for Elo ratings
SURFACES = ['hard', 'grass', 'clay']

# Function to update Elo based on match result and surface
def update_elo(winner_elo, loser_elo, k=32):
    """
    Update Elo ratings for the winner and loser on a given surface.
    k: K-factor which determines how much the rating changes after each match.
    """
    # Calculate expected scores
    expected_winner = 1 / (1 + 10 ** ((loser_elo - winner_elo) / 400))
    expected_loser = 1 / (1 + 10 ** ((winner_elo - loser_elo) / 400))
    
    # Update ratings
    new_winner_elo = winner_elo + k * (1 - expected_winner)
    new_loser_elo = loser_elo + k * (0 - expected_loser)
    
    return new_winner_elo, new_loser_elo

# Function to get player's Elo rating for a given surface and overall
def get_player_elo(player_id, surface):
    """
    Get the current Elo rating for the player on a specific surface and overall.
    Initialize ratings if the player is new.
    """
    if player_id not in player_elo:
        # Initialize the player's ratings for all surfaces and overall
        player_elo[player_id] = {
            'total': INITIAL_ELO,
            'Hard': INITIAL_ELO,
            'Grass': INITIAL_ELO,
            'Clay': INITIAL_ELO
        }
    return player_elo[player_id]['total'], player_elo[player_id][surface]

# Process dataset row by row (assumes data is sorted by match date)
def calculate_surface_elo_for_matches(dataset):
    """
    dataset: Pandas DataFrame containing historical match data.
    Columns should include at least 'match_date', 'player1', 'player2', 'winner', 'surface'.
    """
    # List to store updated Elo ratings for each match
    elo_ratings = []

    for idx, row in dataset.iterrows():
        # Get players and surface for this match
        player1 = row['winner_id']
        player2 = row['loser_id']
        winner = row['winner_id']  # Assumes 'winner' column indicates who won the match
        surface = row['surface']  # Get the surface of the match (e.g., 'hard', 'grass', 'clay')
        
        # Get current total and surface-specific Elo ratings for both players
        player1_total_elo, player1_surface_elo = get_player_elo(player1, surface)
        player2_total_elo, player2_surface_elo = get_player_elo(player2, surface)

        # Add ELO ratings to the row for each player (total and surface-specific)
        dataset.loc[idx, 'winner_elo'] = player1_total_elo
        dataset.loc[idx, 'loser_elo'] = player2_total_elo
        dataset.loc[idx, f'winner_{surface}_elo'] = (0.5 * player1_surface_elo) + (0.5 * player1_total_elo)
        dataset.loc[idx, f'loser_{surface}_elo'] = (0.5 * player2_surface_elo) + (0.5 * player2_total_elo)
        
        # Determine the loser
        #if winner == player1:
        # Update Elo for total and specific surface ratings
        new_winner_total, new_loser_total = update_elo(player1_total_elo, player2_total_elo)
        new_winner_surface, new_loser_surface = update_elo(player1_surface_elo, player2_surface_elo)
        
        # Update Elo ratings for both players (total and surface-specific)
        player_elo[player1]['total'] = new_winner_total
        player_elo[player2]['total'] = new_loser_total
        player_elo[player1][surface] = new_winner_surface
        player_elo[player2][surface] = new_loser_surface

    return dataset
           
df_matches.sort_values('tourney_date', inplace=True)
df_matches = df_matches[df_matches['surface'] != "Carpet"]
df_matches.dropna(subset=['surface', 'w_2ndWon', 'minutes'], axis=0, inplace=True)
df_with_elo = calculate_surface_elo_for_matches(df_matches)

df_with_elo

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,loser_rank,loser_rank_points,winner_elo,loser_elo,winner_Hard_elo,loser_Hard_elo,winner_Clay_elo,loser_Clay_elo,winner_Grass_elo,loser_Grass_elo
0,2023-9900,United Cup,Hard,18,A,20230102,300,126203,3.0,NaN,...,16.0,2375.0,1500.000000,1500.000000,1500.000000,1500.000000,NaN,NaN,NaN,NaN
78,2023-2843,Adelaide 1,Hard,32,A,20230102,270,200615,NaN,Q,...,6.0,4195.0,1500.000000,1500.000000,1500.000000,1500.000000,NaN,NaN,NaN,NaN
77,2023-2843,Adelaide 1,Hard,32,A,20230102,271,106218,NaN,NaN,...,68.0,740.0,1500.000000,1500.000000,1500.000000,1500.000000,NaN,NaN,NaN,NaN
76,2023-2843,Adelaide 1,Hard,32,A,20230102,272,111456,NaN,NaN,...,67.0,741.0,1500.000000,1500.000000,1500.000000,1500.000000,NaN,NaN,NaN,NaN
75,2023-2843,Adelaide 1,Hard,32,A,20230102,273,106415,NaN,NaN,...,11.0,2888.0,1500.000000,1500.000000,1500.000000,1500.000000,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2761,2023-7696,NextGen Finals,Hard,8,F,20231127,290,209098,6.0,NaN,...,70.0,756.0,1556.200117,1475.986467,1559.940488,1465.242067,NaN,NaN,NaN,NaN
2765,2023-7696,NextGen Finals,Hard,8,F,20231127,286,209098,6.0,NaN,...,185.0,326.0,1568.570405,1444.109575,1571.691211,1466.048157,NaN,NaN,NaN,NaN
2764,2023-7696,NextGen Finals,Hard,8,F,20231127,287,209406,8.0,NaN,...,97.0,653.0,1433.607998,1487.593843,1454.755990,1474.756356,NaN,NaN,NaN,NaN
2762,2023-7696,NextGen Finals,Hard,8,F,20231127,289,209414,2.0,NaN,...,185.0,326.0,1463.616179,1452.074321,1453.491344,1471.667306,NaN,NaN,NaN,NaN
2759,2023-7696,NextGen Finals,Hard,8,F,20231127,292,208134,7.0,NaN,...,100.0,640.0,1415.698600,1492.474942,1427.651999,1497.557607,NaN,NaN,NaN,NaN

In [103]:
df_with_elo['winner_surf_elo'] = df_with_elo.apply(lambda x: x['winner_Hard_elo'] if 
                                                   x['surface']=='Hard' else (x['winner_Clay_elo'] if 
                                                                              x['surface']=='Clay' else x['winner_Grass_elo']),axis=1)
df_with_elo['loser_surf_elo'] = df_with_elo.apply(lambda x: x['loser_Hard_elo'] if 
                                                   x['surface']=='Hard' else (x['loser_Clay_elo'] if 
                                                                              x['surface']=='Clay' else x['loser_Grass_elo']),axis=1)
df_with_elo

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,winner_elo,loser_elo,winner_Hard_elo,loser_Hard_elo,winner_Clay_elo,loser_Clay_elo,winner_Grass_elo,loser_Grass_elo,winner_surf_elo,loser_surf_elo
0,2023-9900,United Cup,Hard,18,A,20230102,300,126203,3.0,NaN,...,1500.000000,1500.000000,1500.000000,1500.000000,NaN,NaN,NaN,NaN,1500.000000,1500.000000
78,2023-2843,Adelaide 1,Hard,32,A,20230102,270,200615,NaN,Q,...,1500.000000,1500.000000,1500.000000,1500.000000,NaN,NaN,NaN,NaN,1500.000000,1500.000000
77,2023-2843,Adelaide 1,Hard,32,A,20230102,271,106218,NaN,NaN,...,1500.000000,1500.000000,1500.000000,1500.000000,NaN,NaN,NaN,NaN,1500.000000,1500.000000
76,2023-2843,Adelaide 1,Hard,32,A,20230102,272,111456,NaN,NaN,...,1500.000000,1500.000000,1500.000000,1500.000000,NaN,NaN,NaN,NaN,1500.000000,1500.000000
75,2023-2843,Adelaide 1,Hard,32,A,20230102,273,106415,NaN,NaN,...,1500.000000,1500.000000,1500.000000,1500.000000,NaN,NaN,NaN,NaN,1500.000000,1500.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2761,2023-7696,NextGen Finals,Hard,8,F,20231127,290,209098,6.0,NaN,...,1556.200117,1475.986467,1559.940488,1465.242067,NaN,NaN,NaN,NaN,1559.940488,1465.242067
2765,2023-7696,NextGen Finals,Hard,8,F,20231127,286,209098,6.0,NaN,...,1568.570405,1444.109575,1571.691211,1466.048157,NaN,NaN,NaN,NaN,1571.691211,1466.048157
2764,2023-7696,NextGen Finals,Hard,8,F,20231127,287,209406,8.0,NaN,...,1433.607998,1487.593843,1454.755990,1474.756356,NaN,NaN,NaN,NaN,1454.755990,1474.756356
2762,2023-7696,NextGen Finals,Hard,8,F,20231127,289,209414,2.0,NaN,...,1463.616179,1452.074321,1453.491344,1471.667306,NaN,NaN,NaN,NaN,1453.491344,1471.667306
2759,2023-7696,NextGen Finals,Hard,8,F,20231127,292,208134,7.0,NaN,...,1415.698600,1492.474942,1427.651999,1497.557607,NaN,NaN,NaN,NaN,1427.651999,1497.557607

In [107]:
df_with_elo.reset_index(inplace=True)
df_with_elo.drop("index", axis=1, inplace=True)
df_with_elo.reset_index(inplace=True)
df_with_elo.rename(columns={"index":"match_id"}, inplace=True)
df_with_elo

,match_id,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,...,winner_elo,loser_elo,winner_Hard_elo,loser_Hard_elo,winner_Clay_elo,loser_Clay_elo,winner_Grass_elo,loser_Grass_elo,winner_surf_elo,loser_surf_elo
0,0,2023-9900,United Cup,Hard,18,A,20230102,300,126203,3.0,...,1500.000000,1500.000000,1500.000000,1500.000000,NaN,NaN,NaN,NaN,1500.000000,1500.000000
1,1,2023-2843,Adelaide 1,Hard,32,A,20230102,270,200615,NaN,...,1500.000000,1500.000000,1500.000000,1500.000000,NaN,NaN,NaN,NaN,1500.000000,1500.000000
2,2,2023-2843,Adelaide 1,Hard,32,A,20230102,271,106218,NaN,...,1500.000000,1500.000000,1500.000000,1500.000000,NaN,NaN,NaN,NaN,1500.000000,1500.000000
3,3,2023-2843,Adelaide 1,Hard,32,A,20230102,272,111456,NaN,...,1500.000000,1500.000000,1500.000000,1500.000000,NaN,NaN,NaN,NaN,1500.000000,1500.000000
4,4,2023-2843,Adelaide 1,Hard,32,A,20230102,273,106415,NaN,...,1500.000000,1500.000000,1500.000000,1500.000000,NaN,NaN,NaN,NaN,1500.000000,1500.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2735,2735,2023-7696,NextGen Finals,Hard,8,F,20231127,290,209098,6.0,...,1556.200117,1475.986467,1559.940488,1465.242067,NaN,NaN,NaN,NaN,1559.940488,1465.242067
2736,2736,2023-7696,NextGen Finals,Hard,8,F,20231127,286,209098,6.0,...,1568.570405,1444.109575,1571.691211,1466.048157,NaN,NaN,NaN,NaN,1571.691211,1466.048157
2737,2737,2023-7696,NextGen Finals,Hard,8,F,20231127,287,209406,8.0,...,1433.607998,1487.593843,1454.755990,1474.756356,NaN,NaN,NaN,NaN,1454.755990,1474.756356
2738,2738,2023-7696,NextGen Finals,Hard,8,F,20231127,289,209414,2.0,...,1463.616179,1452.074321,1453.491344,1471.667306,NaN,NaN,NaN,NaN,1453.491344,1471.667306
2739,2739,2023-7696,NextGen Finals,Hard,8,F,20231127,292,208134,7.0,...,1415.698600,1492.474942,1427.651999,1497.557607,NaN,NaN,NaN,NaN,1427.651999,1497.557607

In [108]:
df_with_elo.to_csv("atp_matches_elo_TEST.csv", index=False)

In [81]:
import math
import numpy as np

# Constants for Glicko and Glicko-2 (these can vary)
TAU = 0.5  # Glicko-2 volatility constant
INITIAL_RATING = 1500
INITIAL_RD = 350  # High RD indicates high uncertainty for new players
INITIAL_VOLATILITY = 0.06  # Initial volatility for Glicko-2

# Dictionary to store player Glicko ratings
player_glicko = {}

# Function to initialize a player's Glicko rating, RD, and volatility (for Glicko-2)
def initialize_glicko_player(player_name):
    """
    Initialize Glicko or Glicko-2 rating, RD, and volatility for a player.
    """
    if player_name not in player_glicko:
        player_glicko[player_name] = {
            'rating': INITIAL_RATING,
            'rd': INITIAL_RD,
            'volatility': INITIAL_VOLATILITY}#,  # For Glicko-2
            #'Hard': {'rating': INITIAL_RATING, 'rd': INITIAL_RD, 'volatility': INITIAL_VOLATILITY},
            #'Grass': {'rating': INITIAL_RATING, 'rd': INITIAL_RD, 'volatility': INITIAL_VOLATILITY},
            #'Clay': {'rating': INITIAL_RATING, 'rd': INITIAL_RD, 'volatility': INITIAL_VOLATILITY}}

# Function to calculate the Glicko-2 rating update
def glicko_2_update(rating, rd, volatility, outcomes, tau=TAU):
    """
    Update a player's Glicko-2 rating, RD, and volatility based on match outcomes.
    outcomes: List of tuples (opponent_rating, opponent_rd, outcome), where outcome is 1 for win, 0 for loss.
    """
    # Step-by-step implementation of Glicko-2 algorithm
    # 1. Convert ratings and RDs to Glicko-2 scale
    def g(r):
        return 1 / math.sqrt(1 + 3 * (r ** 2) / (math.pi ** 2))

    def E(player_rating, opponent_rating, opponent_rd):
        return 1 / (1 + np.exp(-g(opponent_rd) * (player_rating - opponent_rating)))

    # 2. Calculate variance (v)
    v_inv = sum([g(opponent_rd) ** 2 * E(rating, opponent_rating, opponent_rd) *
                (1 - E(rating, opponent_rating, opponent_rd)) for opponent_rating, opponent_rd, _ in outcomes])
    v = 1 / v_inv if v_inv > 0 else float('inf')

    # 3. Calculate the delta
    delta = sum([g(opponent_rd) * (outcome - E(rating, opponent_rating, opponent_rd)) for opponent_rating, opponent_rd, outcome in outcomes]) * v

    # 4. Update the volatility (for Glicko-2)
    a = math.log(volatility ** 2)
    def f(x):
        top = (np.exp(x) * (delta ** 2 - rating ** 2 - v - np.exp(x))) / (2 * (rating ** 2 + v + np.exp(x)) ** 2)
        bottom = (x - a) / (tau ** 2)
        return top - bottom

    # Using Newton's method or another technique to solve for new volatility
    # (Solving the above equation numerically)

    # 5. Update RD and rating based on new volatility
    new_rd = 1 / math.sqrt(1 / rd ** 2 + 1 / v)
    new_rating = rating + (new_rd ** 2) * sum([g(opponent_rd) * (outcome - E(rating, opponent_rating, opponent_rd)) for opponent_rating, opponent_rd, outcome in outcomes])

    return new_rating, new_rd, volatility  # Placeholder for new volatility (needs solving above)

# Process dataset row by row (assumes data is sorted by match date)
def calculate_glicko_for_matches(dataset):
    """
    dataset: Pandas DataFrame containing historical match data.
    Columns should include at least 'match_date', 'player1', 'player2', 'winner', 'surface'.
    """
    for idx, row in dataset.iterrows():
        # Get players and surface for this match
        player1 = row['winner_id']
        player2 = row['loser_id']
        #winner = row['winner_id']
        #surface = row['surface']
        
        # Initialize Glicko or Glicko-2 ratings for new players
        initialize_glicko_player(player1)
        initialize_glicko_player(player2)

        # Get current ratings, RDs, and volatilities for both players
        player1_rating, player1_rd, player1_vol = player_glicko[player1]['rating'], player_glicko[player1]['rd'], player_glicko[player1]['volatility']
        player2_rating, player2_rd, player2_vol = player_glicko[player2]['rating'], player_glicko[player2]['rd'], player_glicko[player2]['volatility']
        #print("winner init rating", player1_rating)
        #print("loser init rating", player2_rating)
        # Determine the loser
        #if winner == player1:
        outcome1, outcome2 = 1, 0

        # Collect outcomes for Glicko update
        outcomes1 = [(player2_rating, player2_rd, outcome1)]
        outcomes2 = [(player1_rating, player1_rd, outcome2)]

        # Update Glicko-2 ratings, RDs, and volatilities
        new_player1_rating, new_player1_rd, new_player1_vol = glicko_2_update(player1_rating, player1_rd, player1_vol, outcomes1)
        new_player2_rating, new_player2_rd, new_player2_vol = glicko_2_update(player2_rating, player2_rd, player2_vol, outcomes2)
        #print("new winner rating", new_player1_rating)
        #print("new loser rating", new_player2_rating)
        #if idx > 5:
        #    break
        # Update the player dictionaries with new ratings
        player_glicko[player1]['rating'], player_glicko[player1]['rd'], player_glicko[player1]['volatility'] = new_player1_rating, new_player1_rd, new_player1_vol
        player_glicko[player2]['rating'], player_glicko[player2]['rd'], player_glicko[player2]['volatility'] = new_player2_rating, new_player2_rd, new_player2_vol

        # Store the updated values in the dataset for both players
        dataset.at[idx, 'winner_glicko_rating'] = player1_rating
        dataset.at[idx, 'loser_glicko_rating'] = player2_rating
        dataset.at[idx, 'winner_glicko_rd'] = player1_rd
        dataset.at[idx, 'loser_glicko_rd'] = player2_rd
        dataset.at[idx, 'winner_glicko_volatility'] = player1_vol
        dataset.at[idx, 'loser_glicko_volatility_'] = player2_vol

    return dataset

# Assuming you have a Pandas DataFrame `df` with match history
# df = pd.read_csv('tennis_matches.csv')
df_with_elo.sort_values('tourney_date', inplace=True)

df_with_glicko = calculate_glicko_for_matches(df_with_elo)
df_with_glicko

/var/folders/0d/x4rwj6g110q6_40dfrr6d09w0000gn/T/ipykernel_44989/2924729098.py:118: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_with_elo.sort_values('tourney_date', inplace=True)
/var/folders/0d/x4rwj6g110q6_40dfrr6d09w0000gn/T/ipykernel_44989/2924729098.py:47: RuntimeWarning: invalid value encountered in double_scalars
  delta = sum([g(opponent_rd) * (outcome - E(rating, opponent_rating, opponent_rd)) for opponent_rating, opponent_rd, outcome in outcomes]) * v
/var/folders/0d/x4rwj6g110q6_40dfrr6d09w0000gn/T/ipykernel_44989/2924729098.py:39: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-g(opponent_rd) * (player_rating - opponent_rating)))
/var/folders/0d/x4rwj6g110q6_40dfrr6d09w0000gn/T/ipykernel_44989/2924729098.py:44: RuntimeWarning: overflow encountered in double_scalars
  v = 1 / v_inv if v_inv > 0 else float('inf')

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,winner_Clay_elo,loser_Clay_elo,winner_Grass_elo,loser_Grass_elo,winner_glicko_rating,loser_glicko_rating,winner_glicko_rd,loser_glicko_rd,winner_glicko_volatility,loser_glicko_volatility_
17302,2016-0451,Doha,Hard,32,A,20160104,300,104925,1.0,NaN,...,NaN,NaN,NaN,NaN,1500.000000,1500.000000,350.000000,350.000000,0.06,0.06
17271,2016-0891,Chennai,Hard,32,A,20160104,300,104527,1.0,NaN,...,NaN,NaN,NaN,NaN,1500.000000,1500.000000,350.000000,350.000000,0.06,0.06
17280,2016-0451,Doha,Hard,32,A,20160104,278,103926,NaN,NaN,...,NaN,NaN,NaN,NaN,1500.000000,1500.000000,350.000000,350.000000,0.06,0.06
17279,2016-0451,Doha,Hard,32,A,20160104,277,104871,7.0,NaN,...,NaN,NaN,NaN,NaN,1500.000000,1500.000000,350.000000,350.000000,0.06,0.06
17278,2016-0451,Doha,Hard,32,A,20160104,276,103908,NaN,NaN,...,NaN,NaN,NaN,NaN,1500.000000,1500.000000,350.000000,350.000000,0.06,0.06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4072,2024-0322,Geneva,Clay,32,A,20240520,280,210506,NaN,NaN,...,1508.541022,1465.392784,NaN,NaN,55071.591175,-3098.573460,253.651147,136.425948,0.06,0.06
4057,2024-0322,Geneva,Clay,32,A,20240520,297,104925,1,NaN,...,1943.475687,1595.696997,NaN,NaN,1671.607495,-20218.818786,0.242299,214.802176,0.06,0.06
4070,2024-0322,Geneva,Clay,32,A,20240520,283,133430,NaN,WC,...,1569.422305,1561.013873,NaN,NaN,528.919012,-27771.086659,34.171164,291.239487,0.06,0.06
4075,2024-0322,Geneva,Clay,32,A,20240520,277,207686,NaN,NaN,...,1565.457619,1593.700150,NaN,NaN,-105841.457308,11266.628327,340.140992,346.857898,0.06,0.06
4087,2024-7694,Lyon,Clay,32,A,20240520,294,122330,2,NaN,...,1571.443523,1609.178130,NaN,NaN,1265.147386,-33208.484162,77.549459,195.523047,0.06,0.06

In [77]:
df_with_glicko

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,winner_Clay_elo,loser_Clay_elo,winner_Grass_elo,loser_Grass_elo,winner_glicko_rating,loser_glicko_rating,winner_glicko_rd,loser_glicko_rd,winner_glicko_volatility,loser_glicko_volatility_
17302,2016-0451,Doha,Hard,32,A,20160104,300,104925,1.0,NaN,...,NaN,NaN,NaN,NaN,1500.0,1500.0,350.0,350.0,0.06,0.06
17227,2016-M020,Brisbane,Hard,32,A,20160104,282,105777,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17219,2016-M020,Brisbane,Hard,32,A,20160104,272,103285,NaN,PR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17220,2016-M020,Brisbane,Hard,32,A,20160104,273,106071,7.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17221,2016-M020,Brisbane,Hard,32,A,20160104,275,104471,NaN,Q,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4097,2024-7694,Lyon,Clay,32,A,20240520,283,205734,NaN,NaN,...,1546.811405,1552.288059,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4104,2024-7694,Lyon,Clay,32,A,20240520,275,200384,NaN,Q,...,1486.950933,1431.444807,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4073,2024-0322,Geneva,Clay,32,A,20240520,279,134457,NaN,Q,...,1491.491025,1534.975391,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4055,2024-0322,Geneva,Clay,32,A,20240520,299,207830,NaN,NaN,...,1590.135246,1972.278326,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4087,2024-7694,Lyon,Clay,32,A,20240520,294,122330,2,NaN,...,1571.443523,1609.178130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
#df_matches.drop(['winner_seed','winner_entry','winner_ht', 'loser_seed','loser_entry','loser_ht', 'draw_size'],axis=1,inplace=True)
df_matches.isna().sum()[-20:]

l_df                      0
l_svpt                    0
l_1stIn                   0
l_1stWon                  0
l_2ndWon                  0
l_SvGms                   0
l_bpSaved                 0
l_bpFaced                 0
winner_rank              61
winner_rank_points       61
loser_rank              197
loser_rank_points       197
winner_elo                0
loser_elo                 0
winner_Hard_elo        9028
loser_Hard_elo         9028
winner_Clay_elo       15311
loser_Clay_elo        15311
winner_Grass_elo      19823
loser_Grass_elo       19823
dtype: int64

In [56]:
22081-19823

2258

In [48]:
df_with_elo[df_with_elo['tourney_date']> 20161231]

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,loser_rank,loser_rank_points,winner_elo,loser_elo,winner_Hard_elo,loser_Hard_elo,winner_Clay_elo,loser_Clay_elo,winner_Grass_elo,loser_Grass_elo
20195,2017-0891,Chennai,Hard,32,A,20170102,282,104229,8.0,NaN,...,97.0,614.0,1520.792270,1424.444335,1511.506889,1435.280424,NaN,NaN,NaN,NaN
20220,2017-0451,Doha,Hard,32,A,20170102,277,103333,6.0,NaN,...,74.0,705.0,1618.788305,1429.527832,1595.452254,1443.526463,NaN,NaN,NaN,NaN
20177,2017-M020,Brisbane,Hard,32,A,20170102,292,104745,5.0,NaN,...,51.0,874.0,1687.444659,1560.784508,1638.497234,1563.602296,NaN,NaN,NaN,NaN
20204,2017-0891,Chennai,Hard,32,A,20170102,292,106421,NaN,NaN,...,64.0,754.0,1504.238381,1532.465628,1510.983751,1524.062816,NaN,NaN,NaN,NaN
20223,2017-0451,Doha,Hard,32,A,20170102,280,106210,NaN,NaN,...,507.0,73.0,1554.731291,1500.000000,1513.734185,1500.000000,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4072,2024-0322,Geneva,Clay,32,A,20240520,280,210506,NaN,NaN,...,88.0,668.0,1542.470094,1484.322329,NaN,NaN,1506.860456,1466.325132,NaN,NaN
4069,2024-0322,Geneva,Clay,32,A,20240520,284,105870,NaN,NaN,...,75.0,728.0,1563.481699,1613.272637,NaN,NaN,1553.887482,1625.834955,NaN,NaN
4068,2024-0322,Geneva,Clay,32,A,20240520,286,134770,2,NaN,...,45.0,1010.0,1872.450053,1556.844022,NaN,NaN,1859.997960,1533.822061,NaN,NaN
4056,2024-0322,Geneva,Clay,32,A,20240520,298,134770,2,NaN,...,56.0,860.0,1876.924337,1645.537136,NaN,NaN,1864.248169,1609.777267,NaN,NaN
4087,2024-7694,Lyon,Clay,32,A,20240520,294,122330,2,NaN,...,57.0,849.0,1704.880991,1642.431813,NaN,NaN,1596.153147,1611.957931,NaN,NaN